// This file is automatically generated. DO NOT EDIT

export function __init__() {
  return window['py']['main']['app']['__init__']();
}
        
export function greet() {
  return window['py']['main']['app']['greet']();
}
        
export function get_files() {
  return window['py']['main']['app']['get_files']();
}
        
export function set_dir(path) {
  return window['py']['main']['app']['set_dir'](path);
}
        
export function go_back() {
  return window['py']['main']['app']['go_back']();
}
        
export function get_file_content(path) {
  return window['py']['main']['app']['get_file_content'](path);
}
        