# flake8: noqa
import logging
from pathlib import Path


from proton.utils.code_generator import get_js_code, get_js_bindings

logger = logging.getLogger(__name__)


def test_get_js_code():
    res = get_js_code(current_dir=str(Path(__file__).parent), filename="sample_module.py")
    assert res == """window['py'] = {}; window['py']['main'] = {}; window['py']['main']['app'] = {};
            window['py']['main']['app']['method1'] = async function method1() {
                return await window.pywebview.api.method1();
            }
            
            window['py']['main']['app']['method2'] = async function method2(a, b, c) {
                return await window.pywebview.api.method2(a, b, c);
            }
            """

def test_get_js_bindings():
    res = get_js_bindings(current_dir=str(Path(__file__).parent), filename="sample_module.py")
    assert res == """// This file is automatically generated. DO NOT EDIT

export function method1() {
  return window['py']['main']['app']['method1']();
}
        
export function method2(a, b, c) {
  return window['py']['main']['app']['method2'](a, b, c);
}
        """
